server:
  port: 8085
spring:
  application:
    name: profile-service
  data:
    mongodb:
      database: profiles
      uri: mongodb://localhost:27017/profiles
  sleuth:
    sampler:
      probability: 1.0