server:
  port: 8088
spring:
  application:
    name: proxy
eureka:
  client:
    service-url:
      defaultZone:
        http://localhost:8761/eureka/

openApi.list:
  /api/rest/auth/login, /api/rest/auth/registration



jwt.secret:
  SuperSecret

login.service.name:
  login-service

