server:
  port: 8080

mediastorage:
  path: ./../media_storage/
  video: videos/
  photo: photos/

spring:
  application:
    name: media-storage
  redis:
    host: localhost
    port: 6379
  sleuth:
    sampler:
      probability: 1.0
  cloud:
    bus:
      enabled: true
      env:
        enabled: true
      refresh:
        enabled: true
    config:
      enabled: false

management:
  endpoints:
    web:
      exposure:
        include:
          - busrefresh